GET https://localhost:4300/api/compromissos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3NjVhMjY4OC00NzY0LTQ3YzAtODU3Mi0wOGRjZWUwNGZiYzciLCJlbWFpbCI6InRlc3RlQGdtYWlsLmNvbSIsInVuaXF1ZV9uYW1lIjoidGVzdGUiLCJnaXZlbl9uYW1lIjoidGVzdGUiLCJuYmYiOjE3Mjk3MDQ2NDAsImV4cCI6MTczMDEzNjY0MCwiaWF0IjoxNzI5NzA0NjQwLCJpc3MiOiJlQWdlbmRhIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdCJ9.JjeGfSrg8LyoYOnPuUP3qMsbX6l08EPlGm35tcUpOb8
